# Generated by Django 3.1rc1 on 2020-07-25 14:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resettoken',
            name='expires_on',
            field=models.DateTimeField(
                default=datetime.datetime(2020, 7, 26, 14, 17, 47, 329647, tzinfo=utc)
            ),
        ),
    ]
