# Generated by Django 3.1rc1 on 2020-07-28 08:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_auto_20200728_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resettoken',
            name='expires_on',
            field=models.DateTimeField(
                default=datetime.datetime(2020, 7, 29, 8, 46, 34, 108964, tzinfo=utc)
            ),
        ),
    ]
